<?php if ( ! defined("BASEPATH")) exit("No direct script access allowed");

$config['roles'] = array('admin','users','master');

$config['permission'] = array(
'roles' => array( 
'index' => array('admin','master','users'),
'add' => array('admin','master','users'),
'edit' => array('admin','master','users'),
'delete' => array('admin','master','users'),
'delete_all' => array('admin','master','users'),
'manage' => array('admin','master','users'),
'export' => array('admin','master','users'),
'print' => array('admin','master','users'),
'activate' => array('admin','master','users'),
),
'website_pages' => array( 
'index' => array('admin','master','users'),
'add' => array('admin','master','users'),
'edit' => array('admin','master','users'),
'delete' => array('admin','master','users'),
'delete_all' => array('admin','master','users'),
'manage' => array('admin','master','users'),
'export' => array('admin','master','users'),
'print' => array('admin','master','users'),
'activate' => array('admin','master','users'),
),
'images' => array( 
'index' => array('admin','master','users'),
'add' => array('admin','master','users'),
'edit' => array('admin','master','users'),
'delete' => array('admin','master','users'),
'delete_all' => array('admin','master','users'),
'manage' => array('admin','master','users'),
'export' => array('admin','master','users'),
'print' => array('admin','master','users'),
'activate' => array('admin','master','users'),
),
'users' => array( 
'index' => array('admin','master','users'),
'add' => array('admin','master','users'),
'edit' => array('admin','master','users'),
'delete' => array('admin','master','users'),
'delete_all' => array('admin','master','users'),
'manage' => array('admin','master','users'),
'export' => array('admin','master','users'),
'print' => array('admin','master','users'),
'activate' => array('admin','master','users'),
),
'recycle' => array( 
'index' => array('admin','master','users'),
'add' => array('admin','master','users'),
'edit' => array('admin','master','users'),
'delete' => array('admin','master','users'),
'delete_all' => array('admin','master','users'),
'manage' => array('admin','master','users'),
'export' => array('admin','master','users'),
'print' => array('admin','master','users'),
'activate' => array('admin','master','users'),
),
'static_words' => array( 
'index' => array('admin','master','users'),
'add' => array('admin','master','users'),
'edit' => array('admin','master','users'),
'delete' => array('admin','master','users'),
'delete_all' => array('admin','master','users'),
'manage' => array('admin','master','users'),
'export' => array('admin','master','users'),
'print' => array('admin','master','users'),
'activate' => array('admin','master','users'),
),
'languages' => array( 
'index' => array('admin','master','users'),
'add' => array('admin','master','users'),
'edit' => array('admin','master','users'),
'delete' => array('admin','master','users'),
'delete_all' => array('admin','master','users'),
'manage' => array('admin','master','users'),
'export' => array('admin','master','users'),
'print' => array('admin','master','users'),
'activate' => array('admin','master','users'),
),
'routes' => array( 
'index' => array('admin','master','users'),
'add' => array('admin','master','users'),
'edit' => array('admin','master','users'),
'delete' => array('admin','master','users'),
'delete_all' => array('admin','master','users'),
'manage' => array('admin','master','users'),
'export' => array('admin','master','users'),
'print' => array('admin','master','users'),
'activate' => array('admin','master','users'),
),
'note_labels' => array( 
'index' => array('admin','master','users'),
'add' => array('admin','master','users'),
'edit' => array('admin','master','users'),
'delete' => array('admin','master','users'),
'delete_all' => array('admin','master','users'),
'manage' => array('admin','master','users'),
'export' => array('admin','master','users'),
'print' => array('admin','master','users'),
'activate' => array('admin','master','users'),
),
'emails_templates' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'news' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'news' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'banner' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'news' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'history_of_products' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'history_timeline' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'divisions' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'categories' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'products_lines' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'products' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'products_tags' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'products_tabs' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'environmental_and_csr' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'global_policy' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'site_policy' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'service_centers' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'countries' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'states' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'service_centers_products' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'feedback_types' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'careers_divisions' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'departments' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'regions' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'experience_levels' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'careers_applications' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'document_types' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'products_languages' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'product_keys' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'operating_systems' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'emulations' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'product_support' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'corporate_profile_categories' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'corporate_profile' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'branches' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'seo' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'roles_permissions' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'users_permissions' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
);
?>